name: Test Lambda Webhook
on: workflow_dispatch
jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: |
          node -v
          npm -v
      - name: python command
        shell: bash
        run: python sleep.py
  run-command-2:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: |
          pip --version
          python --version
      - name: python command
        shell: python
        run: print('hello from python')
