name: Test Webhook
on: 
  repository_dispatch:
    types: [run]
  workflow_dispatch:
  # push:
jobs:
  run-command:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: echo a string
        run: |
          echo "hello from webhook"
          
      - name: python command
        shell: bash
        run: python3 sleep.py
        
  run-command-2:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: |
          pip3 --version
          python3 --version


